Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "opscode-centos-7.2"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box"
  c.vm.hostname = "rancher-server-centos-72"
  c.vm.network(:private_network, {:ip=>"192.168.43.33"})
  c.vm.network(:forwarded_port, {:guest=>8080, :host=>8080, :auto_correct=>true})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
