---

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19
  client_rb:
    environment: dev1

platforms:
  - name: centos-7.2

suites:
  - name: slave
    driver:
      network: 
        - ["private_network", {ip: "192.168.33.35"}]
      name: vagrant
    run_list:
      - recipe[bluefinops_jenkins::slave]
      - recipe[bluefinops_sudo]
    attributes: {
      'bluefinops_sudo': {'user': 'jenkins', 'passwordless': true}
    } 
  - name: slave-2
    driver:
      network: 
        - ["private_network", {ip: "192.168.33.36"}]
      name: vagrant
    run_list:
      - recipe[bluefinops_jenkins::slave]
      - recipe[bluefinops_sudo]
    attributes: {
      'bluefinops_sudo': {'user': 'jenkins', 'passwordless': true}
    } 
  - name: master
    driver:
      network: 
        - ["forwarded_port", {guest: 8080, host: 8080}]
        - ["private_network", {ip: "192.168.33.34"}]
      name: vagrant
    run_list:
        - recipe[bluefinops_jenkins]
    attributes: {'bluefinops_jenkins': {'revision': '1.651.3-1.1'}}
    #attributes: {
    #  'bluefinops_jenkins': {'ldap': {'jenkins_username': 'jenkins-auth', 'jenkins_password': 'u1k+J7SJchoKYUnDQrZp'}},
    #  'endpoints': {'ldap': '172.16.0.108'}
    #}
